-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'TARGET_VERIFICATION_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'TARGET_REFUSED';
ALTER TYPE "AuditAction" ADD VALUE 'TARGET_SCOPE_CHANGED';

-- AlterTable
ALTER TABLE "scan_job" ADD COLUMN     "includedPaths" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "excludedPaths" TEXT[] DEFAULT ARRAY[]::TEXT[];
