-- =============================================================================
-- Website Vulnerability Scanner (WVS) - Custom Database Triggers & Policies
-- =============================================================================
-- NOTE: In accordance with NFR-MAINT-1, all custom database functions, triggers,
-- and privilege policies are canonically maintained and executed inside versioned
-- migrations:
--   packages/database/prisma/migrations/20260907000000_init/migration.sql
--
-- This standalone file is deprecated to prevent DDL divergence across environments.
-- For local bootstrap and role provisioning, refer to:
--   packages/database/scripts/bootstrap-roles.sql
-- =============================================================================
